#!/bin/bash
##
# create ubuntu .deb package (according to https://wiki.ubuntu.com/PackagingGuide/Complete )
# (create maintainer gpg key first)
##


# maintainer
export DEBFULLNAME="Daniel Hiepler"
export DEBEMAIL="daniel-ubuntu@niftylight.de"
# repository
REPO=../../../niftyled.git
# debian files
DEBIAN="$(pwd)/debian"
# source package name
SRC_NAME="libniftyled"
# package name
PKG_NAME="${SRC_NAME}$($REPO/version.sh --api-revision)"
# package version
PKG_VERSION="$($REPO/version.sh --long)"
PKG_VERSION_SHORT="$($REPO/version.sh --short)"
# dh_make license
LICENSE=gpl3
# temporary path
TMP="`pwd`/${SRC_NAME}-deb-build"



function die()
{
    echo "Error: $1"
    exit 1
}


if ! [ -d "${TMP}" ] ; then mkdir ${TMP} || die "mkdir" ; fi
DIR="${TMP}/${SRC_NAME}-${PKG_VERSION_SHORT}"

if ! [ -e "${DEBIAN}/control" ] ; then echo "No debian/control file found. Run ./configure once to create one" ; die "no control file" ; fi

# clone repo
if test -d "${DIR}" ; then
 cd ${DIR} || die "cd"
 git pull || die "git"
else
 git clone "${REPO}" "${DIR}" || die "git"
 cd ${DIR} || die "cd"
fi

# configure
autoreconf -i || die "autoreconf"

# create debian files
rm -Rf ${DIR}/debian 2>/dev/null
dh_make --templates "${DEBIAN}" --copyright "${LICENSE}" --email "${DEBEMAIL}" --createorig --library || die "dh_make"
cp "${DEBIAN}/package.dirs" "${DIR}/debian/${PKG_NAME}.dirs"
cp "${DEBIAN}/package.install" "${DIR}/debian/${PKG_NAME}.install"

rm "${DIR}/debian"/*.ex "${DIR}/debian"/*.EX

# build source
dpkg-buildpackage -S -v"${PKG_VERSION}" || die "source pkg build"

# build binary
dpkg-buildpackage -b -v"${PKG_VERSION}" || die "binary pkg build"


cd -
#rm -Rf "${DIR}"

echo "Done. All files in \"${TMP}\""
